### ISSUE TITLE
Photo_invalid_dimensions

### ISSUE THREAD

**Issue by qcgzxw** [qcgzxw/ebook-sender-bot#53]
send photo failed.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/telegram/ext/dispatcher.py", line 557, in process_update
    handler.handle_update(update, self, check, context)
  File "/usr/local/lib/python3.10/dist-packages/telegram/ext/handler.py", line 199, in handle_update
    return self.callback(update, context)
  File "/app/app/tg_bot/tg_bot.py", line 80, in command_warp
    return command(*args, **kwargs)
  File "/app/app/tg_bot/tg_bot.py", line 77, in command
    return command_func(self, update, context)
  File "/app/app/tg_bot/tg_bot.py", line 180, in document
    raise e
  File "/app/app/tg_bot/tg_bot.py", line 168, in document
    send_book_meta(document.get_book_meta())
  File "/app/app/tg_bot/tg_bot.py", line 158, in send_book_meta
    update.message.reply_photo(open(book_meta['cover_path'], 'rb'))
  File "/usr/local/lib/python3.10/dist-packages/telegram/message.py", line 1163, in reply_photo
    return self.bot.send_photo(
  File "/usr/local/lib/python3.10/dist-packages/telegram/bot.py", line 133, in decorator
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/telegram/bot.py", line 732, in send_photo
    return self._message(  # type: ignore[return-value]
  File "/usr/local/lib/python3.10/dist-packages/telegram/ext/extbot.py", line 202, in _message
    result = super()._message(
  File "/usr/local/lib/python3.10/dist-packages/telegram/bot.py", line 339, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/telegram/bot.py", line 298, in _post
    return self.request.post(
  File "/usr/local/lib/python3.10/dist-packages/telegram/utils/request.py", line 359, in post
    result = self._request_wrapper('POST', url, fields=data, **urlopen_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/telegram/utils/request.py", line 279, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Photo_invalid_dimensions
```

**Comment by qcgzxw** [comment]
related: https://github.com/nickoala/telepot/issues/135
telegram api: image size limit
